Redesign services page
codurance/site pull request #493
Opened 2017-01-03 13:17 UTC by mashooq

2017-01-03 13:26 UTC, jukecraft requested changes
Found a few possible improvements

2017-01-03 13:26 UTC, franziskas commented on _i18n/en.yml
> +   subtitle: We understand that everyone is diffrent and will tailor our approach according to the needs of your business and organisation. We will help you build well-crafted software that is valuab
We understand that everyone is different and will tailor our approach according to the needs of your business and organisation. We will help you build well-crafted software that is relevant to your needs. We provide <strong>teams</strong> to create valuable, in-time, and quality software, <strong>expert advise</strong> to fast-track your initiatives, and <strong>training and coaching</strong> to better equip your developers with the right skills and attitudes.

2017-01-03 13:26 UTC, franziskas commented on _i18n/en.yml
> +   subtitle: We will provide fully functional teams to help you deliver your project in the most effective and timely manner. Our craftsmen cover all the roles required for an Agile software develope
We will provide fully functional teams to help you deliver your project in the most effective and timely manner. Our craftsmen cover all the roles required for an agile software development team. We have experts in UX and UI design, Mobile, Front End and Back End Development, DevOps culture and Testing.

2017-01-03 13:26 UTC, franziskas commented on _i18n/en.yml
> +   subtitle: We have expertise in designing visual identity and user experiences. We understand how this effort fits best in an Agile Softeware Deveopment environment. We will help you build the bran
We have expertise in designing visual identity and user experiences. We understand how this effort fits best in an Agile Software Development environment. We will help you build the brand identity and create UX and UI designs as part of your software development effort.

2017-01-03 13:26 UTC, franziskas commented on _i18n/en.yml
> +   subtitle: We will review and help create an apporach to evolve your architecture towards an agreed vision. We have deep knowledge and experience in cloud technologies and enterprise architectures,
We will review and help create an approach to evolve your architecture towards an agreed vision. We have deep knowledge and experience in cloud technologies and enterprise architectures, including Domain Driven Design, Microservices, Event Sourcing and serverless architectures.

2017-01-03 13:26 UTC, franziskas commented on _i18n/en.yml
> +   subtitle: XP practices are core to every Craftsman in Codurance. We love to coach and mentor our customers in adopting these. We advise on how to adopt XP practices and Softeware Craftsmanship val
XP practices are core to everyone at Codurance. We love to coach and mentor our customers in adopting them. We advise on how to adopt XP practices and Software Craftsmanship values to bring about positive change in software development teams.

2017-01-03 13:26 UTC, franziskas commented on services/index.html
> +          <p>We offer taining to help develpers adopt practices such as Test Driven Development, Continuous Integration, and Release Automation. We can also customise our trainings according to the n
We offer training to help developers adopt practices such as Test Driven Development, Continuous Integration, and Release Automation. We can also customise our trainings according to the needs of your team.

2017-01-03 13:26 UTC, franziskas commented on services/index.html
> +          <p>We will review your current soution and provide training on archicture and technologies specific to your project. For example, we can train your team to evolve your system towards a Micr
We will review your current solution and provide training on architecture and technologies specific to your project. For example, we can train your team to evolve your system towards a Microservices based approach utilising the most suitable offerings from AWS.

2017-01-04 10:26 UTC, srodrigo commented on _i18n/es.yml
> +   subtitle: Entendemos que cada uno es diferente, por lo que adaptamos nuestro enfoque a las necesidades de cada negocio y organización. Le ayudaremos a construir software bien hecho que sea relevan
Actually, on a second thought, maybe "dentro de los plazos establecidos" sounds a bit better in Spanish as a replacement for "in-time". What do you think?

2017-01-04 15:28 UTC, alvarogarcia7 commented
@franziskas Seems that your suggestions have been applied. Still want to suggest changes or are you OK with the changes now?

2017-01-05 10:46 UTC, franziskas commented
@alvarogarcia7 all good!

2017-01-05 10:46 UTC, jukecraft approved these changes

2017-01-06 08:32 UTC, CarlosMChica commented
I just realised that the columns in the "We can help you with" section are not of the same height both in EN & ES.

I'd say that if we can fit the text in the columns to be of the same height the page will look much nicer.

2017-01-06 09:28 UTC, srodrigo commented on services/index.html
> +											<span>{% t services-section_2.retail %}</span>
The Retail and Media buttons don't look correct due to the length of the text. Would anyone mind to have a look at the styling?
<img width="947" alt="screen shot 2017-01-06 at 09 24 02" src="https://cloud.githubusercontent.com/assets/5873601/21713540/6263243a-d3f2-11e6-8d58-28fe8e07d48d.png">

2017-01-06 13:54 UTC, neomatrix369 commented on services/index.html
> +											<span>{% t services-section_2.retail %}</span>
I'll take a look at this and try to push something as soon as I'm done

2017-01-06 14:29 UTC, neomatrix369 commented on services/index.html
> +											<span>{% t services-section_2.retail %}</span>
Looks like @ananogal is already looking at it.

2017-01-09 12:32 UTC, merged