new blog on opinions
codurance/site pull request #526
Opened 2017-01-16 17:47 UTC by mashooq

2017-01-16 18:09 UTC, alvarogarcia7 requested changes

2017-01-16 18:09 UTC, alvarogarcia7 commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +1. A view or judgement formed about something, not necessarily based on fact or knowledge.
Please cite the source for these definitions

2017-01-16 18:09 UTC, alvarogarcia7 commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +“Opinionated” is not bad. Having none, or little, opinion is arguably ineffective. However, the validity of your opinion is extremely relevant. Is your opinion a mere gut-feel or a statement of fact?
Style of quotes: is “Opinionated” valid or do you need "Opinionated" ?

2017-01-16 18:09 UTC, alvarogarcia7 commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +It is interesting that the synonyms include belief, judgement and way of thinking. That is what our opinions are to us. Both meanings of the word are relevant to us as software developers. After all,
Classicist vs Outside-in what? styles of TDD

2017-01-16 18:09 UTC, alvarogarcia7 commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +It is interesting that the synonyms include belief, judgement and way of thinking. That is what our opinions are to us. Both meanings of the word are relevant to us as software developers. After all,
very opinionated bunch: opinion - based on what?

2017-01-16 18:09 UTC, alvarogarcia7 commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +It is interesting that the synonyms include belief, judgement and way of thinking. That is what our opinions are to us. Both meanings of the word are relevant to us as software developers. After all,
> Star Trek vs Star Wars,

Formatting:

> Star Trek vs Star Wars, ...

2017-01-16 18:09 UTC, alvarogarcia7 commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +Synonyms to the word opinion are: belief, judgement, thought(s), school of thought, thinking, way of thinking, mind, point of view, view, viewpoint, outlook, angle, slant, side, attitude, stance, per
Please cite the source for the synonyms

2017-01-16 18:09 UTC, alvarogarcia7 commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +Note: this post is also an opinion at the “intuition” level, deduced from my experiences. If you are interested in better formulating your thoughts and ideas then you may find the theory on [Critical
I'm missing the idea / reference of 'how much do I care about this', which mainly applies to decisions but could also apply to opinions

2017-01-17 09:36 UTC, Gryff commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +A somewhat weaker opinion could one formed from an experience. You can say, “from experience I have seen this to be true”. Just because you have experienced something does not mean that it is true in
could [be] one formed from an experience

2017-01-17 12:10 UTC, mashooq commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +Note: this post is also an opinion at the “intuition” level, deduced from my experiences. If you are interested in better formulating your thoughts and ideas then you may find the theory on [Critical
Not sure what you mean here. Can you explain more?

2017-01-17 12:11 UTC, mashooq commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +Synonyms to the word opinion are: belief, judgement, thought(s), school of thought, thinking, way of thinking, mind, point of view, view, viewpoint, outlook, angle, slant, side, attitude, stance, per
source for definition and synonyms are the same - adding it twice is clumsy so no direct citation needed here.

2017-01-17 12:12 UTC, mashooq commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +It is interesting that the synonyms include belief, judgement and way of thinking. That is what our opinions are to us. Both meanings of the word are relevant to us as software developers. After all,
Made it more explicit.

2017-01-17 12:12 UTC, mashooq commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +It is interesting that the synonyms include belief, judgement and way of thinking. That is what our opinions are to us. Both meanings of the word are relevant to us as software developers. After all,
Added footnote.

2017-01-17 12:13 UTC, mashooq commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +It is interesting that the synonyms include belief, judgement and way of thinking. That is what our opinions are to us. Both meanings of the word are relevant to us as software developers. After all,
Can't see the difference.

2017-01-17 12:13 UTC, mashooq commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +“Opinionated” is not bad. Having none, or little, opinion is arguably ineffective. However, the validity of your opinion is extremely relevant. Is your opinion a mere gut-feel or a statement of fact?
Changed the style of quotes.

2017-01-17 12:20 UTC, alvarogarcia7 commented on _posts/2017-01-16-hierarchy-of-opinion.md
> +Note: this post is also an opinion at the “intuition” level, deduced from my experiences. If you are interested in better formulating your thoughts and ideas then you may find the theory on [Critical
I'm talking about this article, that we have discussed in one of our catchups. Please disregard the title: http://blog.capwatkins.com/the-sliding-scale-of-giving-a-fuck

It's about "how much do I care about the results of this decision". Does this also apply to "how much do I care about this opinion"?

2017-01-17 12:22 UTC, alvarogarcia7 commented
The thing about "the scale of..." is optional.

@mashooq Thanks for addressing my concerns

2017-01-17 13:03 UTC, merged