Translate thanks page
codurance/site pull request #537
Opened 2017-01-20 09:32 UTC by PaNaVTEC

2017-01-26 15:01 UTC, guillemf commented on _i18n/es.yml
> +  get-back-soon: Agradecemos que se haya tomado el tiempo de escribirnos. Nos pondremos en contacto contigo pronto.
You use third person and second in the two sentences. It should be one or the other but not mix both. Ex
Agradecemos que te hayas tomado el tiempo de escribirnos. Nos pondremos en contacto contigo pronto.

or

Agradecemos que se haya tomado el tiempo de escribirnos. Nos pondremos en contacto con usted pronto.

2017-01-26 15:02 UTC, guillemf commented on _i18n/es.yml
> +    Hasta entonces, puedes consultar algunos de nuestros recursos:
Same as above.
Hasta entonces, puedes consultar algunos de nuestros recursos:

or 

Hasta entonces puede consultar alguno de nuestros recursos:

Based on the previous choice.

2017-01-26 15:03 UTC, alvarogarcia7 requested changes

2017-01-26 15:03 UTC, alvarogarcia7 commented on _i18n/es.yml
> +  get-back-soon: Agradecemos que se haya tomado el tiempo de escribirnos. Nos pondremos en contacto contigo pronto.
Agree

2017-01-26 15:25 UTC, PaNaVTEC commented
Changed to use 'tu' instead. Let me know if there is anything else that we can improve. Thanks @guillemf @alvarogarcia7 @ananogal

2017-01-26 15:39 UTC, CarlosMChica commented on _i18n/es.yml
> +    Hasta entonces, puedes consultar algunos de nuestros recursos:
"Nos pondremos en contacto lo antes posible" instead of "nos pondremos en contacto contigo pronto".

Sounds better I'd say

2017-01-26 17:32 UTC, guillemf approved these changes

2017-01-27 09:17 UTC, PaNaVTEC commented on _i18n/es.yml
> +    Hasta entonces, puedes consultar algunos de nuestros recursos:
It sounds better for me "Nos pondremos en contacto contigo pronto" becase we specify to who we are going to contact (contigo).
"Nos pondremos en contacto contigo lo antes posible" works for me as well.
Any other opinion on that ? @alvarogarcia7 @guillemf

2017-01-27 16:23 UTC, alvarogarcia7 commented on _i18n/es.yml
> +    Hasta entonces, puedes consultar algunos de nuestros recursos:
@PaNaVTEC looks good to me

2017-01-27 16:23 UTC, alvarogarcia7 approved these changes

2017-01-27 16:27 UTC, merged