New post file
codurance/site pull request #648
Opened 2017-05-04 11:44 UTC by charlyraffellini

2017-05-04 12:21 UTC, alvarogarcia7 requested changes
Please review the text with a spell checker, then possibly with a native speaker

2017-05-04 12:21 UTC, alvarogarcia7 commented on _posts/2017-05-04-docker-swarm-part-one.md
> ++---+    +---+    +---+
This is not properly displayed on the site

2017-05-04 12:21 UTC, alvarogarcia7 commented on _posts/2017-05-04-docker-swarm-part-one.md
> +```ruby
Not properly formatted

2017-05-04 12:21 UTC, alvarogarcia7 commented on _posts/2017-05-04-docker-swarm-part-one.md
> +
needs formatting as code

2017-05-04 12:21 UTC, alvarogarcia7 commented on _posts/2017-05-04-docker-swarm-part-one.md
> +```
not properly formatted (needs a newline)

2017-05-04 12:21 UTC, alvarogarcia7 commented on _posts/2017-05-04-docker-swarm-part-one.md
> +The concepts that you must learn to run docker swarm are not so differents from the once that you use for run docker instances in a node.
typo: not _differents_ but _different_

2017-05-04 12:21 UTC, alvarogarcia7 commented on _posts/2017-05-04-docker-swarm-part-one.md
> +The concepts that you must learn to run docker swarm are not so differents from the once that you use for run docker instances in a node.
typo: not _once_ but _ones_

2017-05-04 12:21 UTC, alvarogarcia7 commented on _posts/2017-05-04-docker-swarm-part-one.md
> +The concepts that you must learn to run docker swarm are not so differents from the once that you use for run docker instances in a node.
possible typo: not _run_ but _running_ (less sure about this one)

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +[Docker swarm](https://docs.docker.com/engine/swarm/) is a Docker mode to run and manage a cluster of Docker Engines.
When I start to read the post I would like to see what problem the author try to solve. The description of the reason why we would like to configure the cluster of docker engines would be good addition. You can assume that people already know what is Docker.

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +- Service: it is a definition of the kind of task that is going to be run by the cluster. It is the unit of the swarm. Services can be of two types, replicated or global. The last one ensures that at
It would be good to have a more detailed explanation of the difference between replicated and global. This point explains only the role of the last one.

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +- Task: it is the unit which carries the container and the commands to run inside.
To run inside Swarm, Container or Docker engine? A more detailed explanation required. From this description I don't understand the role of tasks in the process. Maybe you can combine the description of these key concepts with the description of the process.

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +## Services and Stack
I don't understand the idea of the stack. Is it the extension to docker-compose or some abstract concept? It is hard to understand why it is `docker stack` in this context. Maybe few examples or some diagram could make it more clear.

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +Showing docker swarm levels:
You don't mention anything about swarm levels in the above description. What is the swarm level?

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +## Vagrant setup
I would name this point "Setting up local environment"

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +For this examples, I am going to use Vagrant. It is not the goal of this post to teach Vagrant, however, I am going to detail how to use this script.
Instead of 

"For this examples, I am going to use Vagrant. I am going to use Vagrant. It is not the goal of this post to teach Vagrant, however, I am going to detail how to use this script "  

I would write: 

"In my post I'm going to use Vagrant to setup all required servers on my local machine  Vagrant is tool ... (few words what it is). We are not going to focus on Vagrant in this post, but I will show all Vagrant scripts which I use during the writing this post." (of course it is very rough proposal. Please polish it ;) )

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +## Vagrant setup
I would also start with some explanation of the roles of managers and workers.

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +In the vagrant definition, we have a set of managers and worker instances. The names are going to be `m1,m2` for the managers and `w1, w2, w3` for the workers. Also, we can hit the manager IPs with `
1. Before describing the details of the Vagrant script I would put some diagram and the description of my setup e.g:
"I'm going to prepare environment with two managers (named in Vagrant 'm1' and 'm2'). ...."

2. What is the "192.168.99.20#{1,2}"? Is it 192.168.99.21 and 192.168.99.22? Are they going to have the same address on all machines (for example if someone will try to reproduce your behaviour on his/her local environment).

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +Create a `docker-swarm-test` directory and create a `Vagrantfile` inside.
Maybe you can create the Github repository with files ready to use. In your post you can put link to this repository and refer to directories in this repo.

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +The `Vagrantfile` we created needs a provisioning script in `./node.bash`.
Why do we need this script?

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +Vagrantfile
You also assume that VBox is installed on the machine. I suggest to put the information that you need to install Vagrant and VBox before you want to start doing the exercise.

Another possible option is to get rid off Vagrant completely from the post and focus on the Swarm. You can mention that you can find the proper Vagrant script in the github repository for this post.

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +I am going to assume that you have docker installed on your machine in order to run commands in the nodes. Also, you can ssh one of the VMs and run docker client from there, however, I recommend to r
Maybe it would be ok to create additional machine with installed docker and git, connected to the same network as the other VMs. It would act as workstation for all exercises.

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +Export Docker host variable with manager address:
Why do we need to do that? An explanation needed.

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +Initialize the swarm manager node:
What is happening during the initialisation? Why do we need to do it?

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +The **SWarM ToKeN** version **1** corresponds to the pattern `SWMTKN-1-< digest-of-root-CA-cert>-< random-secret >`. [Here](https://github.com/docker/labs/tree/master/security/swarm#step-2-add-a-new-
I would explain it before the command

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +Challenge: Try to connect the m2 instance as a manager.
I don't know if it fits the blog post. Maybe you can describe what will happen when you connect to another manager.

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +We are going to create services using `docker stack`. This is a similar to docker-compose but for services. You can always do the same with `docker service`.
It is unclear what is the difference between the stack and the service. Few sentences explaining the difference may be required.

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +swarmrt.yml
Why `...rt...`?

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +        image: charlieraffellini/swarmrt
It would be good to explain that this image must be created before on each node (or maybe I'm wrong).

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +Then it continues with the definition of the services. In this case, we only have one `swarmrt`. Then we continue defining the image that we want to run in the containers, the port we want to expose
What is the replicated mode?

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +In this case, we want to prove that we are behind a load balancer so, we are going to deploy an instance of our container in each node. Let's do it:
How do you want to prove it?

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +So let's prove it. Run `watch -d -n 1 curl -s -4 http://192.168.99.201:9080/`. You will see that every second the IP of who receive the request is different. This is because each time that we send a
It would ok to explain what the command `watch` is doing.

2017-05-04 19:25 UTC, robertfirek commented on _posts/2017-05-04-docker-swarm-part-one.md
> +### Scale down
The topic of this point is more about constrains than scaling. I suggest to split constraints and scaling into separate topics.

2017-05-04 19:50 UTC, charlyraffellini commented on _posts/2017-05-04-docker-swarm-part-one.md
> +        image: charlieraffellini/swarmrt
You don't need to pull any image in any node in order to create a service. Swarm pull it with the right version if you specified one.

2017-05-07 14:21 UTC, charlyraffellini commented
I am closing this PR till I have solved all the comments.

2017-05-07 14:21 UTC, closed without merging