ASOS Case Study, Spanish version
codurance/site pull request #652
Opened 2017-05-08 16:02 UTC by charlyraffellini

2017-05-08 16:25 UTC, srodrigo requested changes
Hey Carlos, I added a few comments.

2017-05-08 16:25 UTC, srodrigo commented on _i18n/es.yml
> +    subtitle: <p>El despliegue manual de muchas etapas, que requería multiples equipos, tenía un impcto negativo en la habilidad de la organización para desplegar cambios regularmente. La metodología
`impcto` is missing an `a`
duplicate `de` on `La metodología de de Software Craftmanship`

2017-05-08 16:25 UTC, srodrigo commented on _i18n/es.yml
> +    about: ASOS es un negocio de moda online, vende moda de vanguardia y apoya una prospera comunidad de moda. Comenzó como un blog de moda, la marca ahora ofrece a sus clientes aplicaciones móviles
Missing tilde on pr**o**spera
I'd say `Comenzando como un blog de moda` - Does anyone else have any thoughts about this?

2017-05-08 16:25 UTC, srodrigo commented on _i18n/es.yml
> +    the_challenge: <p> Con más de 123 millones de visitas a su sitio al mes y con 95 millones visitas por día, ASOS se esforzaba por adaptar sus sistemas y garantizar la performance durante los perío
I'd translate `la performance` into `el rendimiento`

2017-05-08 16:25 UTC, srodrigo commented on _i18n/es.yml
> +                   <p> En un esfuerzo por modernizar y mejorar sus capacidades en IT, ASOS experimentó un programa para mejorar la velocidad del cambio, la facilidad y la tasa de delivery y una mejor
experimentó **con** un programa ? Sounds a bit more natural to me.

2017-05-08 16:25 UTC, srodrigo commented on _i18n/es.yml
> +    our_sc_approach: <p> Ayudamos a construir y re-arquitectar rápidamente algunos de sus sistemas principales, agregando niveles de redundancia y almacenamiento en caché que les permitió hacer frent
`les permitió hacer frente al tráfico de pico` -> would you say? `les permitió hacer frente a picos de tráfico`? I know it's singular, but I can't think of a natural translation.

2017-05-08 16:25 UTC, srodrigo commented on _i18n/es.yml
> +                     <p> El trabajo fue en .NET ASP .NET MVC con bases de datos SQL Azure, alojado en Microsoft Azure. El sitio también empleó algunas tecnologías open source para caché de como Redis
`tecnologías open source para caché de como Redis` -> `tecnologías open source de caché como Redis` o `tecnologías open source para caché como Redis`?

2017-05-08 16:25 UTC, srodrigo commented on _i18n/es.yml
> +                     <p>Si bien sus equipos de desarrollo ya estaban bastante establecidos, particularmente en torno a los procesos ágiles, identificamos la necesidad de que estos equipos fueran perf
`estos equipos fueran perfeccionados técnicas prácticas ágiles` should say something like `estos equipos fueran perfeccionados en técnicas prácticas ágiles`? I know the original is missing the preposition, but sounds a bit strange.

`culture de DevOps` ->  `cultura de DevOps`?

2017-05-08 16:25 UTC, srodrigo commented on _i18n/es.yml
> +             <p>Cambiamos las prácticas técnicas dentro del equipo, mejorando la calidad general del código. Varios miembros que pasaron por los cursos de capacitación han sido promovidos en puestos
`promovidos en` -> does `promocionados a` sound more natural?

2017-05-09 09:46 UTC, charlyraffellini commented on _i18n/es.yml
> +    subtitle: <p>El despliegue manual de muchas etapas, que requería multiples equipos, tenía un impcto negativo en la habilidad de la organización para desplegar cambios regularmente. La metodología
I think `múltiples` is more formal. Which could be a good or a bad thing.

2017-05-11 10:39 UTC, srodrigo approved these changes

2017-05-11 11:10 UTC, merged