WIP: Add Christina to the company page
codurance/site pull request #776
Opened 2017-11-01 10:10 UTC by TrinkeG

2017-11-01 11:34 UTC, richardjwild requested changes
I think we should get a cleaner photograph taken that better matches the others.

2017-11-01 11:34 UTC, richardjwild commented on _data/team.yml
> +    <p>Christina has been working as a software developer and team leader in the .Net Ecosystem for a number of years. Enjoying process automation and generaly making others jobs easier.</p>
"Ecosystem" should not be capitalised.
"Generally" should have double L.
There should be an apostrophe after others, i.e. others'

2017-11-01 11:34 UTC, richardjwild commented on _data/team.yml
> +    <p>Starting out playing with visual basic at 16 she moved on to study development at university and has been coding ever since.</p>
"Visual Basic" should be capitalised.

2017-11-01 11:34 UTC, richardjwild commented on _data/team.yml
> +    <p>Christina has a passion for self-improvement and is allways looking for new learning opportunities accross a variety of subject matters.</p>
"Always" should have single L.

2017-11-01 11:34 UTC, richardjwild commented on _data/team.yml
> +    <p>Outside of work Christina is and avid consumer of sci-fi and fantasy books as well as enjoying weightlifting and bouldering amongst other strength based activities.</p>
"and" -> "an"

2017-11-06 09:26 UTC, richardjwild approved these changes

2017-11-06 13:38 UTC, cyplo commented
Looks good to me, is it still WIP ?

2017-11-08 09:51 UTC, merged